Cherry pick more fixes for feb point2 (#10183)
* Ensure DS auto start code is non-blocking (#10171)

* Perf fixes
* Add news entry

* Include interperter name in message (#10174)

For #10071
Fix to ensure interpreter is included in message, here's the actual message seen by the user.

Error: Jupyter cannot be started. Error attempting to locate jupyter: 'Kernelspec' module not installed in the selected interpreter ({0}).

Note the {0}

* Ignore display name when searching interpreters (#10175)

Partial fix for #10173
Comparing against path of interpreter alone is sufficient.

Figured there's no harm in trying to minimise occurrences of dup kernels (basically just compare against python executable path, as thats sufficient and always accurate)

Display name:

Can change from version to version of Python extension (i.e. it shouldn't have been used as a unique identifier)
Display name can change after extension loads and more information about interpreter is available.

* Track cold/warm times to execute notebook cells (#10180)

For #10176